### ISSUE TITLE
Add install instructions

### ISSUE THREAD

**Issue by blumenthal** [ethz-asl/fw_swm_ros#2]
I did a from scratch ROS installation. Some install instruction would be of great help, since it seems to depend on on a set of ethz-asl packages like: 

* simpleCMake
* glog

**Comment by dymczykm** [comment]
@blumenthal Even though I'm not Timo, I will try to provide a bit of information.

The packages you ask about are catkin packages. If you're not familiar with it, please take a look:
http://wiki.ros.org/catkin/Tutorials

We also use catkin simple, that provides some simplifications when creating packages, you can read about it here: 
https://github.com/catkin/catkin_simple

If there's no rosinstall file for this repo (not sure if there's one), you have to manually checkout repos that provide the missing dependencies to your catkin workspace, i.e.:
https://github.com/ethz-asl/glog_catkin
https://github.com/ethz-asl/gflags_catkin
https://github.com/ethz-asl/opencv2_catkin
https://github.com/ethz-asl/eigen_catkin
(I think the rest of packages should be provided by ROS, but I might be wrong)

**Comment by hitimo** [comment]
@blumenthal Added instructions and script in #3. Feel free to reopen this issue if there are problems.
